export enum Tables {
  USERS = 'users',
  ACCOUNTS = 'accounts',
  USERS_ACCOUNTS = 'users_accounts',
  AUDIT = 'audit',
  COMPANY_DETAILS = 'company_details',
  BANK_DETAILS = 'bank_details',
  TRANSACTIONS = 'transactions',
  TRANSACTION_DISPUTES = 'transaction_disputes',
  TRANSACTION_STAGES = 'transaction_stages',
  TRANSACTION_SIDES = 'transaction_sides',
  COMMISSIONS = 'commissions',
  PRODUCT_CATEGORIES = 'product_categories',
  PRODUCT_PROPERTIES = 'product_properties',
  FILES = 'files',
}
